### ISSUE TITLE
ikmem_destroy()后分配的内存不会释放？？？

### ISSUE THREAD

**Issue by QingruiHuang** [skywind3000/memslab#2]
![2024-04-27_16-08-34](https://github.com/skywind3000/memslab/assets/2128058/dcd9d179-4f6d-44a5-9b7c-ea640d6c9ba1)

ikmem_destroy()后分配的内存不会释放？？？

**Comment by QingruiHuang** [comment]
![2024-04-29_10-59-09](https://github.com/skywind3000/memslab/assets/2128058/8b790bbc-57c7-48cd-ab7d-3e8296d52433)
搞不明白ikmem_destroy()后，先前分配的内存还可以继续使用，这样有没有问题？？？

**Comment by skywind3000** [comment]
只是没帮你清空而已，当然不能继续使用

**Comment by QingruiHuang** [comment]
我只想搞清楚，这种情况，存不存在内存泄漏。

**Comment by skywind3000** [comment]
调用了 ikmem_free 以后当然不存在泄露，但你不能在之后使用了。

**Comment by QingruiHuang** [comment]
看了代码，但不完全看懂；
调用了ikmem_destroy()后->ikmem_free() -> free()，释放了所有malloc()的内存块；
所以最后--3-- 的printf(ptr)应该是异常才对的吧？
但是现在引用ptr没有异常，不是很明白什么原因？
这样的结果是否正常？如正常，为何正常，还请指导说明。

**Comment by skywind3000** [comment]
当然不能继续引用 ptr 了，已经出错了，只是暂时没崩溃而已。c++ 里访问野指针又不会立即出错，但不代表你程序正确，程序稍微复杂点，多来两遍你就 crash 了，这是基础知识啊。

又不是 java 任何错误都能立马详细的告诉你。
